# Generated by Django 4.0.4 on 2022-05-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register_on',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=122)),
                ('child_name', models.CharField(max_length=122)),
                ('guardian_name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phpne', models.CharField(max_length=12)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
