# Generated by Django 4.0.4 on 2022-05-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_on',
            old_name='child_name',
            new_name='childname',
        ),
        migrations.RenameField(
            model_name='register_on',
            old_name='guardian_name',
            new_name='guardianname',
        ),
        migrations.RenameField(
            model_name='register_on',
            old_name='parent_name',
            new_name='parentname',
        ),
        migrations.RenameField(
            model_name='register_on',
            old_name='phpne',
            new_name='phone',
        ),
    ]
